# @date 2018-08-24
# @author Frederic SCHERMA
# @license Copyright (c) 2018 Dream Overflow
# Crypto Alpha strategy default parameters.

from instrument.instrument import Instrument

# magic 8,13,21,55,89,13
DEFAULT_PARAMS = {
    'reversal': True,
    'max-trades': 3,    # max number of simultaned trades for a same market
    'trade-delay': 30,  # at least wait 30 seconds before sending another signal 
    'base-timeframe': Instrument.TF_TICK,   # process each time strategy receive a tick
    'min-traded-timeframe': Instrument.TF_MIN,
    'max-traded-timeframe': Instrument.TF_MIN,
    'sltp-timeframe': Instrument.TF_1H,
    'ref-timeframe': Instrument.TF_4H,
    'need-update': True,      # only compute when update is waited
    'min-vol24h': 100,        # 100 BTC per 24h
    'min-price': 0.00000069,  # or 69 sats
    'region-allow': False,    # don't trade if no defined region
    'timeframes': {
        'weely': {
            'timeframe': Instrument.TF_WEEK,
            'parent': None,
            'mode': 'C',
            'depth': 22,
            'history': 22,
            'score-ratio': 8,
            'score-level': 0.05,
            'indicators': {
                'price': ('price', 1,),
                'volume': ('volume', 0,),
                'rsi': ('rsi', 21,),
                'stochrsi': ('stochrsi', 13, 13, 13),
                'sma': ('sma', 21,),
                'ema': ('ema', 21,),
                'hma': None,
                'vwma': ('vwma', 21,),
                'momentum': ('momentum', 21,),
                'stochastic': None,
                'macd': None,  # ('macd', 21,),
                'bollingerbands': None, # (''bollingerbands', 21,),
                'triangle': None,
                'fibonacci': None,  # ('fibonacci', 15,),
                'pivotpoint': ('pivotpoint', 3,),
                'tomdemark': None,
                'atr': ('atr', 14, 2.618),
            },
            'constants': {
                'rsi_low': 0.3,
                'rsi_high': 0.7,
            },
        },
        'daily': {
            'timeframe': Instrument.TF_DAY,
            'parent': Instrument.TF_WEEK,
            'mode': 'C',
            'depth': 22,
            'history': 22,
            'score-ratio': 8,
            'score-level': 0.05,
            'indicators': {
                'price': ('price', 1,),
                'volume': ('volume', 0,),
                'rsi': ('rsi', 21,),
                'stochrsi': ('stochrsi', 13, 13, 13),
                'sma': ('sma', 20,),
                'ema': ('ema', 20,),
                'hma': None,
                'vwma': ('vwma', 20,),
                'momentum': ('momentum', 20,),
                'stochastic': None,
                'macd': None,  # ('macd', 21,),
                'bollingerbands': ('bollingerbands', 21,),
                'triangle': None,
                'fibonacci': None,  # ('fibonacci', 15,),
                'pivotpoint': ('pivotpoint', 3,),
                'tomdemark': ('tomdemark', 9),
                'atr': ('atr', 14, 2.618),
            },
            'constants': {
                'rsi_low': 0.3,
                'rsi_high': 0.7,
            },
        },
        '4hour': {
            'timeframe': Instrument.TF_4HOUR,
            'parent': Instrument.TF_DAY,
            'mode': 'A',
            'depth': 56,
            'history': 56,
            'score-ratio': 6,
            'score-level': 0.05,
            'indicators': {
                'price': ('price', 1,),
                'volume': ('volume', 0,),
                'rsi': ('rsi', 21,),
                'stochrsi': ('stochrsi', 13, 13, 13),
                'sma': ('sma', 21,),
                'ema': ('ema', 55,),
                'hma': None,
                'vwma': ('vwma', 21,),
                'momentum': ('momentum', 21,),
                'stochastic': None,
                'macd': None,  # ('macd', 21,),
                'bollingerbands': ('bollingerbands', 21,),
                'triangle': None,
                'fibonacci': None,  # ('fibonacci', 15,),
                'pivotpoint': ('pivotpoint', 3,),
                'tomdemark': ('tomdemark', 9),
                'atr': ('atr', 14, 2.618),
            },
            'constants': {
                'rsi_low': 0.3,
                'rsi_high': 0.7,
            }   
        },
        'hourly': {
            'timeframe': Instrument.TF_HOUR,
            'parent': Instrument.TF_4HOUR,
            'mode': 'A',
            'depth': 22,
            'history': 22,
            'score-ratio': 4,
            'score-level': 0.05,
            'indicators': {
                'price': ('price', 1,),
                'volume': ('volume', 0,),
                'rsi': ('rsi', 21,),
                'stochrsi': ('stochrsi', 13, 13, 13),
                'sma': ('sma', 21,),
                'ema': ('ema', 21,),
                'hma': None,
                'vwma': ('vwma', 21,),
                'momentum': ('momentum', 21,),
                'stochastic': None,
                'macd': None,  # ('macd', 17,),
                'bollingerbands': ('bollingerbands', 21,),
                'triangle': None,
                'fibonacci': None,  # ('fibonacci', 15,),
                'pivotpoint': ('pivotpoint', 3,),
                'tomdemark': ('tomdemark', 9),
                'atr': ('atr', 14, 2.618),
            },
            'constants': {
                'rsi_low': 0.3,
                'rsi_high': 0.7,
            }
        },
        '15min': {
            'timeframe': Instrument.TF_15MIN,
            'parent': Instrument.TF_HOUR,
            'mode': 'A',
            'depth': 22,
            'history': 22,
            'score-ratio': 2,
            'score-level': 0.05,
            'indicators': {
                'price': ('price', 1,),
                'volume': ('volume', 0,),
                'rsi': ('rsi', 21,),
                'stochrsi': ('stochrsi', 13, 13, 13),
                'sma': ('sma', 21,),
                'ema': ('ema', 21,),
                'hma': None,
                'vwma': ('vwma', 21,),
                'momentum': ('momentum', 21,),
                'stochastic': None,
                'macd': None,  # ('macd', 17,),
                'bollingerbands': ('bollingerbands', 21,),
                'triangle': None,
                'fibonacci': None,  # ('fibonacci', 15,),
                'pivotpoint': ('pivotpoint', 3,),
                'tomdemark': ('tomdemark', 9),
                'atr': ('atr', 14, 2.618),
            },
            'constants': {
                'rsi_low': 0.3,
                'rsi_high': 0.7,
            }
        },
        '5min': {
            'timeframe': Instrument.TF_5MIN,
            'parent': Instrument.TF_15MIN,
            'mode': 'A',
            'depth': 14,
            'history': 14,
            'score-ratio': 1,
            'score-level': 0.05,
            'indicators': {
                'price': ('price', 1,),
                'volume': ('volume', 0,),
                'rsi': ('rsi', 13,),
                'stochrsi': ('stochrsi', 13, 13, 13),
                'sma': ('sma', 13,),
                'ema': ('ema', 13,),
                'hma': None,
                'vwma': ('vwma', 13,),
                'momentum': ('momentum', 13,),
                'stochastic': None,
                'macd': None,  # ('macd', 17,),
                'bollingerbands': ('bollingerbands', 13,),
                'triangle': None,
                'fibonacci': None,  # ('fibonacci', 15,),
                'pivotpoint': ('pivotpoint', 3,),
                'tomdemark': ('tomdemark', 9),
                'atr': ('atr', 14, 2.618),
            },
            'constants': {
                'rsi_low': 0.3,
                'rsi_high': 0.7,
            }
        },
        '2min': {
            'timeframe': Instrument.TF_2MIN,
            'parent': Instrument.TF_5MIN,
            'mode': 'A',
            'depth': 20,
            'history': 20,
            'score-ratio': 0.5,
            'score-level': 0.05,
            'indicators': {
                'price': ('price', 1,),
                'volume': ('volume', 0,),
                'rsi': ('rsi', 8,),
                'stochrsi': ('stochrsi', 13, 13, 13),
                'sma': ('sma', 20,),
                'ema': ('ema', 8,),
                'hma': ('hma', 8,),
                'vwma': ('vwma', 8,),
                'momentum': ('momentum', 20,),
                'stochastic': None,
                'macd': None,  # ('macd', 17,),
                'bollingerbands': None, # ('bollingerbands', 26,),
                'triangle': None,
                'fibonacci': None,  # ('fibonacci', 15,),
                'pivotpoint': ('pivotpoint', 3,),
                'tomdemark': ('tomdemark', 9),
                'atr': ('atr', 14, 2.618),
            },
            'constants': {
                'rsi_low': 0.3,
                'rsi_high': 0.7,
            }
        },
        '1min': {
            'timeframe': Instrument.TF_MIN,
            'parent': Instrument.TF_MIN,
            'mode': 'A',
            'depth': 20,
            'history': 20,
            'score-ratio': 0.5,
            'score-level': 0.05,
            'indicators': {
                'price': ('price', 1,),
                'volume': ('volume', 0,),
                'rsi': ('rsi', 8,),
                'stochrsi': ('stochrsi', 13, 13, 13),
                'sma': ('sma', 20,),
                'ema': ('ema', 8,),
                'hma': ('hma', 8,),
                'vwma': ('vwma', 8,),
                'momentum': ('momentum', 20,),
                'stochastic': None,
                'macd': None,  # ('macd', 17,),
                'bollingerbands': None, # ('bollingerbands', 26,),
                'triangle': None,
                'fibonacci': None,  # ('fibonacci', 15,),
                'pivotpoint': ('pivotpoint', 3,),
                'tomdemark': ('tomdemark', 9),
                'atr': ('atr', 14, 2.618),
            },
            'constants': {
                'rsi_low': 0.3,
                'rsi_high': 0.7,
            }
        }
    }
}
