#!/bin/bash
# update FROM= each time or use --last= and do it every day/week using a crontab
TO='2020-12-31T23:59:59'
MARKETS=*EUR

FROM='2017'
# python siis.py real --fetch --broker=kraken.com --market=$MARKETS --from=$FROM --to=$TO --timeframe=1d --cascaded=1w
python siis.py real --fetch --broker=kraken.com --market=$MARKETS --update --from=$FROM --to=$TO --timeframe=1d --cascaded=1w

FROM='2017'
# python siis.py real --fetch --broker=kraken.com --market=$MARKETS --from=$FROM --to=$TO --timeframe=4h
python siis.py real --fetch --broker=kraken.com --market=$MARKETS --update --from=$FROM --to=$TO --timeframe=4h

FROM='2017'
# python siis.py real --fetch --broker=kraken.com --market=$MARKETS --from=$FROM --to=$TO --timeframe=1h --cascaded=2h
python siis.py real --fetch --broker=kraken.com --market=$MARKETS --update --from=$FROM --to=$TO --timeframe=1h --cascaded=2h

# FROM='2020-12'
# python siis.py real --fetch --broker=kraken.com --market=$MARKETS --from=$FROM --to=$TO --timeframe=15m --cascaded=30m
# python siis.py real --fetch --broker=kraken.com --market=$MARKETS --from=$FROM --to=$TO --timeframe=5m
# python siis.py real --fetch --broker=kraken.com --market=$MARKETS --from=$FROM --to=$TO --timeframe=1m --cascaded=3m
