#!/bin/bash
# update FROM= each time or use --last= and do it every day/week using a crontab
TO='2019-12-31T23:59:59'

FROM='2019-08-26T00:00:00'
python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --from=$FROM --to=$TO --timeframe=1w &

FROM='2019-08-27T00:00:00'
python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --from=$FROM --to=$TO --timeframe=1d &

FROM='2019-08-27T12:00:00'
python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --from=$FROM --to=$TO --timeframe=4h &

FROM='2019-08-27T12:00:00'
python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --from=$FROM --to=$TO --timeframe=1h 

# FROM='2019-08-27T12:00:00'
# python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --from=$FROM --to=$TO --timeframe=15m
# python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --from=$FROM --to=$TO --timeframe=5m
