#!/bin/bash
# update FROM= each time or use --last= and do it every day/week using a crontab
TO='2020-12-31T23:59:59'

FROM='2020-04-06T00:00:00'
# python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --from=$FROM --to=$TO --timeframe=1w &
python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --update --to=$TO --timeframe=1w &

FROM='2020-04-07T00:00:00'
# python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --from=$FROM --to=$TO --timeframe=1d &
python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --update --to=$TO --timeframe=1d &

FROM='2020-04-07T08:00:00'
# python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --from=$FROM --to=$TO --timeframe=4h &
python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --update --to=$TO --timeframe=4h &

FROM='2020-04-07T08:00:00'
# python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --from=$FROM --to=$TO --timeframe=1h --cascaded=2h
python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --update --to=$TO --timeframe=1h --cascaded=2h

FROM='2020-04-07T08:00:00'
# python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --from=$FROM --to=$TO --timeframe=15m --cascaded=30m
python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --update --to=$TO --timeframe=15m --cascaded=30m

FROM='2020-04-07T08:00:00'
# python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --from=$FROM --to=$TO --timeframe=5m
python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --update --to=$TO --timeframe=5m

# FROM='2019-12-11T00:00:00'
# python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --from=$FROM --to=$TO --timeframe=1m --cascaded=3m
# python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --update--to=$TO --timeframe=1m --cascaded=3m
