#!/bin/bash
MARKETS='CS.D.AUDNZD.MINI.IP,CS.D.EURCAD.MINI.IP,CS.D.EURJPY.MINI.IP,CS.D.EURUSD.MINI.IP,CS.D.GBPUSD.MINI.IP,CS.D.USDJPY.MINI.IP,CS.D.CFEGOLD.CFE.IP,IX.D.SPTRD.IFE.IP,IX.D.DAX.IFMM.IP'
TO='2019-12-31T23:59:59'
IDENTITY='demo'

FROM='2019-08-05T00:00:00'
python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --from=$FROM --to=$TO --timeframe=1w &

FROM='2019-08-07T00:00:00'
python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --from=$FROM --to=$TO --timeframe=1d &

FROM='2019-08-07T08:00:00'
python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --from=$FROM --to=$TO --timeframe=4h &

FROM='2019-08-07T08:00:00'
python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --from=$FROM --to=$TO --timeframe=1h 
