#!/bin/bash
TO='2019-12-31T23:59:59'
MARKETS='XBTUSD,ETHUSD,LTCM19,TRXM19,EOSM19,XRPM19,ADAM19,BCHM19,XBTM19'

# need the last 7 day to reconstruct the weekly
FROM='2019-03-25T00:00:00'
python siis.py real --fetch --broker=bitmex.com --market=$MARKETS --last=50 --timeframe=1d --cascaded=1w

# need the last 4 1h to reconstruct the 4h
FROM='2019-03-25T12:00:00'
python siis.py real --fetch --broker=bitmex.com --market=$MARKETS --last=50 --timeframe=1h --cascaded=4h

# need the last 3 5m to reconstruct the 15m
FROM='2019-03-25T12:00:00'
python siis.py real --fetch --broker=bitmex.com --market=$MARKETS --last=50 --timeframe=5m --cascaded=15m

# need the last 3 5m to reconstruct the 15m
FROM='2019-03-25T12:00:00'
python siis.py real --fetch --broker=bitmex.com --market=$MARKETS --last=50 --timeframe=1m
