#!/bin/bash
# run it before starting live, adjust the number
MARKETS='CS.D.AUDNZD.MINI.IP,CS.D.EURCAD.MINI.IP,CS.D.EURJPY.MINI.IP,CS.D.EURUSD.MINI.IP,CS.D.GBPUSD.MINI.IP,CS.D.USDJPY.MINI.IP,CS.D.CFEGOLD.CFE.IP,IX.D.SPTRD.IFE.IP,IX.D.DAX.IFMM.IP'
IDENTITY='real'

python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --last=120 --timeframe=1w &
python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --last=150 --timeframe=1d &
python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --last=150 --timeframe=4h 
python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --last=150 --timeframe=2h &
python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --last=150 --timeframe=1h 
python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --last=180 --timeframe=30m

# only just before running bot (last 50 15m and last 50 5m)
python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --last=180 --timeframe=15m &
python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --last=100 --timeframe=5m
python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --last=100 --timeframe=3m &
python siis.py $IDENTITY --fetch --broker=ig.com --market=$MARKETS --last=100 --timeframe=1m
