#!/bin/bash
# run it before starting live, adjust the number
MARKETS='*USDT,*BTC'

if [ -z $1 ]; then
    MIN=0
else
    MIN=$1
fi

if [ $MIN = 0 ]; then
    python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --last=1 --timeframe=1w &
    python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --last=1 --timeframe=1d
    python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --last=1 --timeframe=4h &
    python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --last=1 --timeframe=2h
    python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --last=1 --timeframe=1h
fi

python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --last=50 --timeframe=15m &
python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --last=50 --timeframe=5m
python siis.py real --fetch --broker=binance.com --market=*USDT,*BTC --last=50 --timeframe=1m
