#!/bin/bash
# update FROM= each time or use --last= and do it every day/week using a crontab
TO='2019-12-31T23:59:59'

FROM='2019-09-16T00:00:00'
python siis.py real --fetch --broker=kraken.com --market=*ZEUR,*XBT --last=100 --timeframe=1d --cascaded=1w

FROM='2019-09-16T00:00:00'
python siis.py real --fetch --broker=kraken.com --market=*ZEUR,*XBT --last=100 --timeframe=4h

FROM='2019-09-16T00:00:00'
python siis.py real --fetch --broker=kraken.com --market=*ZEUR,*XBT --last=100 --timeframe=1h

FROM='2019-09-16T00:00:00'
python siis.py real --fetch --broker=kraken.com --market=*ZEUR,*XBT --last=100 --timeframe=15m
python siis.py real --fetch --broker=kraken.com --market=*ZEUR,*XBT --last=100 --timeframe=5m
python siis.py real --fetch --broker=kraken.com --market=*ZEUR,*XBT --last=100 --timeframe=1m
